language: ruby

cache: bundler

before_install:
  - gem update bundler

rvm:
  - "2.6"
  - "2.7"
  - "3.0"
  - ruby-head
  - jruby-9.2.17.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: "3.0"
    - rvm: jruby-9.2.17.0
  fast_finish: true

notifications:
  recipients:
    - mail@zzak.io
  slack: sinatrarb:LQGhUfGYcqRgRzwKea0bqUhY
